name: build-deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean verify
      - name: Analyze with SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=todo-service -Dsonar.organization=anant-pawar-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy:
    name: Deploy Service
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE }}
          api-key: ${{ secrets.RENDER_TOKEN }}
  build-docs:
    name: Build Documentation
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: git-checkhot
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        id: redoc-build
        shell: bash
        continue-on-error: true
        run: |
          echo "Building Started" &&  npx redoc-cli build docs/openapi.yaml --title "Todo Service API" &&  mv redoc-static.html index.html && echo "Building Finished"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          exclude_assets: '.github,.mvn,.gitignore,docs,src,README.md,Dockerfile,mvnw,mvnw.cmd,pom.xml'